import type { Metadata } from "next";
// import { Rubik } from "next/font/google";
import "./globals.css";
import YupLocale from "@/components/yup-locale";
import { Toaster } from "@/components/ui/sonner";
import { CheckCircle, WarningCircle } from "@phosphor-icons/react/dist/ssr";

// const font = Rubik({
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ar" dir="rtl">
      <body className="antialiased min-h-[100svh]" style={{ fontFamily: 'system-ui, sans-serif' }}>
        <YupLocale />
        <Toaster
          theme="light"
          toastOptions={{
            // className: font.className,
            classNames: {
              content: "!ps-2",
              error: "!border-red-500",
            },
          }}
          icons={{
            error: <WarningCircle color="red" size={24} />,
            success: <CheckCircle color="green" size={24} />,
          }}
        />
        {children}
      </body>
    </html>
  );
}
